### ISSUE TITLE
Error after updating to Vaadin 24.3.0

### ISSUE THREAD

**Issue by andersforsell** [vaadin-component-factory/selection-grid-flow#47]
After updating to Vaadin 24.3.0 I get the following error:

generated-flow-imports-zoyVtkhd.js:6525  Uncaught TypeError: this._getPageForIndex is not a function
    at o2.nS (generated-flow-imports-zoyVtkhd.js:6525:1343)
    at o2._updateScrollerItem (generated-flow-imports-zoyVtkhd.js:5635:9516)
    at J8.__updateElement (generated-flow-imports-zoyVtkhd.js:5502:3787)
    at J8.<anonymous> (generated-flow-imports-zoyVtkhd.js:5502:6307)
    at J8._iterateItems (generated-flow-imports-zoyVtkhd.js:5498:6025)
    at J8._assignModels (generated-flow-imports-zoyVtkhd.js:5502:6148)
    at J8._update (generated-flow-imports-zoyVtkhd.js:5498:3691)
    at J8._render (generated-flow-imports-zoyVtkhd.js:5498:5209)
    at J8.<anonymous> (generated-flow-imports-zoyVtkhd.js:5498:8205)
    at rp.flush (generated-flow-imports-zoyVtkhd.js:1177:542)
    at generated-flow-imports-zoyVtkhd.js:1177:678
    at Set.forEach (<anonymous>)
    at MA (generated-flow-imports-zoyVtkhd.js:1177:660)
    at rl (generated-flow-imports-zoyVtkhd.js:1177:751)
    at set size [as size] (generated-flow-imports-zoyVtkhd.js:5502:5217)
    at set size [as size] (generated-flow-imports-zoyVtkhd.js:5502:12034)
    at o2._flatSizeChanged (generated-flow-imports-zoyVtkhd.js:5635:2796)
    at Object.Xf [as fn] (generated-flow-imports-zoyVtkhd.js:219:6781)
    at il (generated-flow-imports-zoyVtkhd.js:219:647)
    at o2._propertiesChanged (generated-flow-imports-zoyVtkhd.js:219:12474)
    at E._propertiesChanged (FlowClient-urjGN_YE.js:3:75254)
    at o2._flushProperties (generated-flow-imports-zoyVtkhd.js:193:2560)
    at o2._invalidateProperties (generated-flow-imports-zoyVtkhd.js:219:11429)
    at Object.defineProperty.set (generated-flow-imports-zoyVtkhd.js:193:970)
    at o2._updateColumnTree (generated-flow-imports-zoyVtkhd.js:5555:1030)
    at rp._callback (generated-flow-imports-zoyVtkhd.js:5555:851)
    at generated-flow-imports-zoyVtkhd.js:1177:330
    at CA (generated-flow-imports-zoyVtkhd.js:1169:122)
    at generated-flow-imports-zoyVtkhd.js:1169:683

**Comment by thevaadinman** [comment]
Should be fixed in version 3.0.2.

**Comment by andersforsell** [comment]
Thanks for a quick fix, works fine now!

**Comment by thevaadinman** [comment]
Note, I released 3.0.3 due to user error with the Vaadin Directory causing the 3.0.2 release to not have source and javadoc attached. 3.0.3 is the same as 3.0.2, but with JavaDoc and source.
Apologies for the inconvenience.

**Comment by andersforsell** [comment]
Thanks for fixing.
I just wish this component was part of the standard Vaadin Grid/TreeGrid because at least for tree grids this is the multi-select feature the users expect.
